### ISSUE TITLE
this._parse() error

### ISSUE THREAD

**Issue by vegetableman** [mattdesl/number-editor#1]
@mattdesl Pretty cool project. Found a little bug. There is no method _parse defined.

**Comment by mattdesl** [comment]
Can you try `1.2.3`? I fixed a bug with `_parse` a little while back, but maybe I hadn't published it until now.

Also, updated [the test](https://github.com/mattdesl/number-editor#demo).

**Comment by vegetableman** [comment]
yep works :+1:. The progress bar looks cool. Closing this.
